### ISSUE TITLE
Add support for 2 User-Agents

### ISSUE THREAD

**Issue by innov83r** [kshyju/BrowserDetector#2]
Hello,

Could you add support for the following User Agents:
 
`docker/19.03.5 go/go1.12.12 git-commit/633a0ea kernel/4.9.184-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.5 \(windows\))
` 
`PostmanRuntime/7.21.0` < not sure if this one is possible since there is no indication of OS

I didn't look much at the code after I read your statement about opening a ticket to request more browser/os combos, but I suppose I could take a stab at forking and adding them, if you couldn't.

Thanks!

**Comment by kshyju** [comment]
Hey, Thanks! 

Curious to know what platform these UAs will result in ?

**Comment by innov83r** [comment]
Hey!

I'm building an identity platform that private docker registry can use.

**Comment by innov83r** [comment]
I use postman for testing. And the identity platform will track many
metadata data points.

**Comment by kshyju** [comment]
What browser it will / should resolve into ?

**Comment by innov83r** [comment]
Sorry for the late reply. If it is the Docker-Client UA it should resolve to Docker-Client. If it is the Postman UA it should resolve to Postman.

**Comment by kshyju** [comment]
The goal of the library is to enable light weight pure browser detection. Docker-client in this case is not a pure browser/UA. Isn't it ?

**Comment by innov83r** [comment]
Sorry, I wasn't aware of the purpose of that goal. I will roll my own,
thanks.
