### ISSUE TITLE
GitIgnore

### ISSUE THREAD

**Issue by lars-lange** [kshyju/BrowserDetector#20]
Hi @kshyju ,
I noticed that you added /src/BrowserDetector.NetCore/BrowserDetector.Net.csproj to the cleanup branch's gitignore file
Is that intentional? Since the changes to the project files were not committed, the project was already broken in the past.

Feel free to add me as a reviewer to your cleanup-pr and I'll take a look asap

**Comment by kshyju** [comment]
That is a mistake. That branch is still a WIP and I will make sure to clean up the gitignore before it gets merged to main.

**Comment by lars-lange** [comment]
solved by cleanup
