### ISSUE TITLE
Should handle empty/null user-agent

### ISSUE THREAD

**Issue by hakancunier** [kshyju/BrowserDetector#8]
If the request is made by a HttpClient object, the "User-Agent" header is missing. Since there is no empty/null checking in BrowserDetector.GetBrowser method i get this error

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Primitives.StringValues.get_Item(Int32 index)
   at Shyjus.BrowserDetection.BrowserDetector.GetBrowser()

Can you please fix this?

**Comment by kshyju** [comment]
Apologies for the delayed response. This issue has been fixed in version 2.0.0. Could you use that please ?
https://www.nuget.org/packages/Shyjus.BrowserDetector/2.0.0
